version: 2.1


jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout:
        path: 
      - run:
          name: Build
          command: mvn -f backend/pom.xml -B -DskipTests clean package
      - run:
          name: Test
          command: mvn -f backend/pom.xml test
  

  


orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
      