version: 2.1


jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test


orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
        name: deploy-back
        app-name: rental-app-6
        filters:
          branches:
            only: 
              - deployment
          requires:
            - build-and-test
      - heroku/deploy-via-git:
        name: deploy-front
        app-name: rental-app-6-front
        filters:
          branches:
            only: 
              - deployment
          requires:
            - deploy-back